// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBocOa03x1E5_UWpnUTC_ynCR31jdZvfT8',
    appId: '1:1087149830892:web:c3b892e32dd829adc3ebc9',
    messagingSenderId: '1087149830892',
    projectId: 'asar-cd2ba',
    authDomain: 'asar-cd2ba.firebaseapp.com',
    databaseURL: 'https://asar-cd2ba-default-rtdb.firebaseio.com',
    storageBucket: 'asar-cd2ba.appspot.com',
    measurementId: 'G-CLVND7ZR1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhFz2fX6bN2a0jKHC1tqdXC7LrbRmtjk',
    appId: '1:1087149830892:android:fd20031728f6cfadc3ebc9',
    messagingSenderId: '1087149830892',
    projectId: 'asar-cd2ba',
    databaseURL: 'https://asar-cd2ba-default-rtdb.firebaseio.com',
    storageBucket: 'asar-cd2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI5E1I_7EW0KCr1Hccz_N5OQyT-u7s2Fk',
    appId: '1:1087149830892:ios:d75cdab7d6be3905c3ebc9',
    messagingSenderId: '1087149830892',
    projectId: 'asar-cd2ba',
    databaseURL: 'https://asar-cd2ba-default-rtdb.firebaseio.com',
    storageBucket: 'asar-cd2ba.appspot.com',
    iosBundleId: 'tinetv.media.tinetv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI5E1I_7EW0KCr1Hccz_N5OQyT-u7s2Fk',
    appId: '1:1087149830892:ios:d75cdab7d6be3905c3ebc9',
    messagingSenderId: '1087149830892',
    projectId: 'asar-cd2ba',
    databaseURL: 'https://asar-cd2ba-default-rtdb.firebaseio.com',
    storageBucket: 'asar-cd2ba.appspot.com',
    iosBundleId: 'tinetv.media.tinetv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPLKxcnt4_NUoE4r_dAHLNZ3QVOkq8QpI',
    appId: '1:1087149830892:web:92709ede23ee580fc3ebc9',
    messagingSenderId: '1087149830892',
    projectId: 'asar-cd2ba',
    authDomain: 'asar-cd2ba.firebaseapp.com',
    databaseURL: 'https://asar-cd2ba-default-rtdb.firebaseio.com',
    storageBucket: 'asar-cd2ba.appspot.com',
    measurementId: 'G-7ZDV0R3NZR',
  );
}
